server:
  port: 8080

logging:
  level:
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG
    com.example.Svoi: DEBUG

jwt:
  secret: z2L4R9tWdLxZ0i9Xv0Cjv7Gey+8m8OcgT+8WJGhNQHPqXTm2EJvHt8DrL3NKq9Ur3ZTFvA1dH3JhqqcytxkutdhMtA8Dw==
  expiration: 86400000
  header: Authorization
  prefix: Bearer

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/svoi_db
    username: postgres
    password: admin
environment:
  - SPRING_PROFILES_ACTIVE=docker
